### ISSUE TITLE
Add i18n to spread the world :)

### ISSUE THREAD

**Issue by Guts** [dav-apps/UniversalSoundboard#3]
Hi,

Thanks for your app: useful, nice, stable and simple to use.

To make it even easier to use, could you add an option to select the UI language to use please? It'll help to spread the world!
It can be a manual settings in the "General" or the "Design" tab, not need for an automatic detection.

If you add the i18n process I can add the French and Spanish translations :)

**Comment by Dav2070** [comment]
Hi, thank you very much for the feedback :)

The idea for i18n is very interesting. I'm thinking about creating some kind of platform so that everyone can create and improve translations for their own language, but it will take some time (maybe next year).
By then I would also add the option to select the language manually.

In the meantime, I would really appreciate it if you could create translations for French and Spanish manually. I would then include it in the next update :)

You can find the file for English here:
[https://github.com/Dav2070/UniversalSoundboard/blob/master/UniversalSoundBoard/Strings/en-US/Resources.resw](https://github.com/Dav2070/UniversalSoundboard/blob/master/UniversalSoundBoard/Strings/en-US/Resources.resw)
Just copy it, replace the strings with the translation and send it to me (or create a pull request).

**Comment by Guts** [comment]
Ok I'll make a PR :)

> I'm thinking about creating some kind of platform so that everyone can create and improve translations for their own language,

Why not Transifex? ;)

**Comment by Dav2070** [comment]
I didn't know Transifex until just now, but I will take a look :)

**Comment by Dav2070** [comment]
Looks nice
![image](https://user-images.githubusercontent.com/16546287/60287208-9d0ed700-9911-11e9-9207-1f11ce09505a.png)
The update is on its way :)
